# Generated by Django 6.0.4 on 2026-04-16 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the skill or service', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what you offer')),
                ('category', models.CharField(choices=[('tutoring', 'Tutoring'), ('tech', 'Tech & Programming'), ('design', 'Design'), ('writing', 'Writing & Editing'), ('music', 'Music & Arts'), ('fitness', 'Fitness & Sports'), ('language', 'Language Exchange'), ('professional', 'Professional Services'), ('other', 'Other')], default='other', max_length=50)),
                ('is_free', models.BooleanField(default=False, help_text='Check if you offer this for free')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per session/service (leave blank if free)', max_digits=10, null=True)),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('in_person', 'In Person'), ('online', 'Online')], default='email', max_length=50)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('busy', 'Busy')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
